version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,dynamodb,s3
      - DATA_DIR=/tmp/localstack/data
#      - DEBUG=1
    ports:
      - "4566:4566"
      - "8080:8080"
    volumes:
      - ./serverless:/tmp/localstack/serverless
